version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Docker/node/Dockerfile  # Specify the path to the Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 of the host
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase  # MongoDB connection string
    depends_on:
      - mongo

  mongo:
    image: mongo:latest  # Use the latest MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo-data:/data/db  # Use a volume to persist data

volumes:
  mongo-data: